export const REACT_APP_API_URL =
  process.env.REACT_APP_API_URL || 'PLACEHOLDER_REACT_APP_API_URL';

export const REACT_APP_ENVIRONMENT =
  process.env.REACT_APP_ENVIRONMENT || 'PLACEHOLDER_REACT_APP_ENVIRONMENT';
